name = "vedfinance-web"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
NEXT_PUBLIC_API_URL = "https://api.hocchungkhoan.com.vn"
